language: php

php: ["5.3", "5.4", "5.5"]

env:
  global:
    - ARCHER_PUBLISH_VERSION=5.5
    - secure: "WZ/TFW00WqAtt6eb3+0gE+R+WXhMjAln/mSjAg5cT/zzWPyJMfAp/sZpuoWCWZefvnCzGFP5iyF+n8R3Tvru0p6KQGJkJltBvPR4NFQkG1qG/IRjM8oMxmkW9mEjfqrUdHLULfjrJpMPoaoNMjjZKHLxSKBx0Ywz1KSG+AvIHhk="

install:
  - ./.travis.install

script:
  - ./vendor/bin/archer travis:build
