sudo: false
language: php
php:
- '7.2'
- '7.3'
- '7.4'
- nightly
matrix:
  fast_finish: true
  allow_failures:
  - php: nightly
before_install:
- phpenv config-rm xdebug.ini || true
- "[[ $GITHUB_TOKEN ]] && composer config --global github-oauth.github.com $GITHUB_TOKEN"
install: composer install --no-interaction
script: phpdbg -qrr vendor/bin/phpunit
after_script: bash <(curl -s https://codecov.io/bash)
env:
  global:
    secure: "eh25ZdxT3BnaSlvRWGcV6pwwKxcHCqlxhMOqMTK2xlhitst8UNg6K1Cq7qA1fgFeV/itfl7lmuZyI6McezmwsfU5ocBGy/pMutF3KIGs+uxqknucNWVGjKiv6HsXxEktTG7pvR/90OAJXFhPQlji+6l0p9At6zBkYL3CnZK3Ei0="
cache:
  directories:
  - "$HOME/.composer/cache/files"
