language: php

php: ["5.3", "5.4", "5.5", "5.6", "7.0", "7.1", "hhvm"]

matrix:
    allow_failures: [{"php": "7.1"}, {"php": "hhvm"}]
    fast_finish: true

env:
  global:
    - ARCHER_PUBLISH_VERSION=7.0
    - secure: "WZ/TFW00WqAtt6eb3+0gE+R+WXhMjAln/mSjAg5cT/zzWPyJMfAp/sZpuoWCWZefvnCzGFP5iyF+n8R3Tvru0p6KQGJkJltBvPR4NFQkG1qG/IRjM8oMxmkW9mEjfqrUdHLULfjrJpMPoaoNMjjZKHLxSKBx0Ywz1KSG+AvIHhk="

install:
  - ./.travis.install

script:
  - ./vendor/bin/archer travis:build
