language: php

php: ["7.0", "7.1", "nightly"]

matrix:
    allow_failures: [{"php": "7.1"}, {"php": "nightly"}]
    fast_finish: true

env:
  global:
    - secure: "WZ/TFW00WqAtt6eb3+0gE+R+WXhMjAln/mSjAg5cT/zzWPyJMfAp/sZpuoWCWZefvnCzGFP5iyF+n8R3Tvru0p6KQGJkJltBvPR4NFQkG1qG/IRjM8oMxmkW9mEjfqrUdHLULfjrJpMPoaoNMjjZKHLxSKBx0Ywz1KSG+AvIHhk="

install:
  - ./.travis.install

script:
  - ./vendor/bin/archer travis:build
